services:
  - type: web
    name: getransfr-server
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    # optional: expose the port your server listens on (default 3000)
    # envVars:
    #   - key: PORT
    #     value: 3000